import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Splash from './Splash.jsx';
import NavLayout from './NavLayout.jsx';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Splash>
          <NavLayout>
            {children}
          </NavLayout>
        </Splash>
      </body>
    </html>
  )
}
